name: ec2 health check

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: ssh to ec2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_PUBLIC_IP }}
      - name: check cpu
        run: top -b -n1
      - name: check memory
        run: fese -m
      - name: check disk space
        run: df -h
