name: java ci/cd
on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven -y
          mvn -version
          java -version
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        with:
          args: --file=CalculatorProject/pom.xml
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Build with maven
        run: |
          mvn clean install
        working-directory: CalculatorProject
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-jar_v1
          path: CalculatorProject/target/*.jar
  
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
        - name: download-artifact
          uses: actions/download-artifact@v4
          with:
            name: calculator-jar_v1
        - name: setup key
          run: |
            echo "${{ secrets.KEY }}" > key.pem
            chmod 400 key.pem    
        - name: copy jar to ec2
          run: scp -i key.pem calculator-jar_v1/*.jar ubuntu@"${{ secrets.ip }}":/home/ubuntu/calculator.jar
        - name: run jar on ec2
          run: |
            ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@"${{ secrets.ip }}" << 'EOF'
               echo "ssh succesfull"
               cd /home/ubuntu
               echo "switched to home/ubuntu"
               nohup java -jar calculator.jar --server.port=8081 > output.log 2>&1 &
               echo "jar is running"
            EOF


 